require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CredentialsController do

  # This should return the minimal set of attributes required to create a valid
  # Credential. As you add validations to Credential, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CredentialsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all credentials as @credentials" do
      credential = Credential.create! valid_attributes
      get :index, {}, valid_session
      assigns(:credentials).should eq([credential])
    end
  end

  describe "GET show" do
    it "assigns the requested credential as @credential" do
      credential = Credential.create! valid_attributes
      get :show, {:id => credential.to_param}, valid_session
      assigns(:credential).should eq(credential)
    end
  end

  describe "GET new" do
    it "assigns a new credential as @credential" do
      get :new, {}, valid_session
      assigns(:credential).should be_a_new(Credential)
    end
  end

  describe "GET edit" do
    it "assigns the requested credential as @credential" do
      credential = Credential.create! valid_attributes
      get :edit, {:id => credential.to_param}, valid_session
      assigns(:credential).should eq(credential)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Credential" do
        expect {
          post :create, {:credential => valid_attributes}, valid_session
        }.to change(Credential, :count).by(1)
      end

      it "assigns a newly created credential as @credential" do
        post :create, {:credential => valid_attributes}, valid_session
        assigns(:credential).should be_a(Credential)
        assigns(:credential).should be_persisted
      end

      it "redirects to the created credential" do
        post :create, {:credential => valid_attributes}, valid_session
        response.should redirect_to(Credential.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved credential as @credential" do
        # Trigger the behavior that occurs when invalid params are submitted
        Credential.any_instance.stub(:save).and_return(false)
        post :create, {:credential => {}}, valid_session
        assigns(:credential).should be_a_new(Credential)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Credential.any_instance.stub(:save).and_return(false)
        post :create, {:credential => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested credential" do
        credential = Credential.create! valid_attributes
        # Assuming there are no other credentials in the database, this
        # specifies that the Credential created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Credential.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => credential.to_param, :credential => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested credential as @credential" do
        credential = Credential.create! valid_attributes
        put :update, {:id => credential.to_param, :credential => valid_attributes}, valid_session
        assigns(:credential).should eq(credential)
      end

      it "redirects to the credential" do
        credential = Credential.create! valid_attributes
        put :update, {:id => credential.to_param, :credential => valid_attributes}, valid_session
        response.should redirect_to(credential)
      end
    end

    describe "with invalid params" do
      it "assigns the credential as @credential" do
        credential = Credential.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Credential.any_instance.stub(:save).and_return(false)
        put :update, {:id => credential.to_param, :credential => {}}, valid_session
        assigns(:credential).should eq(credential)
      end

      it "re-renders the 'edit' template" do
        credential = Credential.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Credential.any_instance.stub(:save).and_return(false)
        put :update, {:id => credential.to_param, :credential => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested credential" do
      credential = Credential.create! valid_attributes
      expect {
        delete :destroy, {:id => credential.to_param}, valid_session
      }.to change(Credential, :count).by(-1)
    end

    it "redirects to the credentials list" do
      credential = Credential.create! valid_attributes
      delete :destroy, {:id => credential.to_param}, valid_session
      response.should redirect_to(credentials_url)
    end
  end

end
